package:
    name:           yii2-merchant
    namespace:      hiqdev\yii2\merchant
    title:          Payment merchants extension for Yii2
    type:           yii2-extension
    keywords:       yii2, merchant, PayPal, WebMoney, Yandex.Money, eCoin, Paxum, OKpay, Qiwi, InterKassa, RoboKassa
    description:    Payment merchants extension for Yii2

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
