package:
    type:           yii2-extension
    name:           yii2-merchant
    title:          Yii2 extension for payment processing with Omnipay, Payum and more later
    headline:       Yii2 Merchant
    keywords:       yii2, merchant, payment, omnipay, payum
    namespace:      hiqdev\yii2\merchant
    description:    |
        This [Yii2](http://yiiframework.com/) extension provides payment gateways integration with use of
        [Omnipay](http://omnipay.thephpleague.com/) and [Payum](http://payum.org/) payment processing libraries.

